from __future__ import annotations

import csv
import json
from pathlib import Path

from tools import flight_log_sysid as sysid


HEADER = [
    "timestamp_us",
    "sequence",
    "dropped_records",
    "sector_seq",
    "sector_index",
    "roll_deg",
    "pitch_deg",
    "gyro_x_dps",
    "gyro_y_dps",
    "gyro_z_dps",
    "vel_est_m_s_0",
    "vel_est_m_s_1",
    "vel_ref_m_s_0",
    "vel_ref_m_s_1",
    "vel_err_m_s_0",
    "vel_err_m_s_1",
    "vel_pid_out_m_s2_0",
    "vel_pid_out_m_s2_1",
    "vel_pid_p_m_s2_0",
    "vel_pid_p_m_s2_1",
    "vel_pid_i_m_s2_0",
    "vel_pid_i_m_s2_1",
    "vel_pid_d_m_s2_0",
    "vel_pid_d_m_s2_1",
    "vel_loop_active",
    "throttle_us",
    "servo_alpha_us",
    "servo_beta_us",
    "motor_upper_us",
    "motor_lower_us",
    "motor_output_reason_name",
    "ctrl_total_force_n",
    "ctrl_pos_p_m_s2_0",
    "ctrl_pos_p_m_s2_1",
    "ctrl_vel_d_m_s2_0",
    "ctrl_vel_d_m_s2_1",
    "ctrl_accel_out_m_s2_0",
    "ctrl_accel_out_m_s2_1",
    "ctrl_target_attitude_rp_rad_0",
    "ctrl_target_attitude_rp_rad_1",
    "ctrl_tilt_angle_p_rad_0",
    "ctrl_tilt_angle_p_rad_1",
    "ctrl_tilt_rate_d_rad_0",
    "ctrl_tilt_rate_d_rad_1",
    "ctrl_tilt_out_rad_0",
    "ctrl_tilt_out_rad_1",
    "ctrl_attitude_error_0",
    "ctrl_attitude_error_1",
    "ctrl_rate_error_rad_s_0",
    "ctrl_rate_error_rad_s_1",
    "ctrl_moment_cmd_n_m_0",
    "ctrl_moment_cmd_n_m_1",
    "ctrl_horizontal_command_scale",
    "ctrl_moment_utilization",
    "ctrl_thrust_utilization",
    "ctrl_protection_flags",
]


def test_default_channels_include_flow_and_actual_servo_bus_data() -> None:
    assert "servo_alpha_sent_us" in sysid.DEFAULT_CHANNELS
    assert "flow_height_raw_m" in sysid.DEFAULT_CHANNELS
    assert "flow_optical_rot_comp_m_s_0" in sysid.DEFAULT_CHANNELS
    assert "flow_offset_rot_comp_m_s_1" in sysid.DEFAULT_CHANNELS
    assert "servo_feedback_timeout_count" in sysid.DEFAULT_CHANNELS


def write_sample_log(tmp_path: Path) -> Path:
    csv_path = tmp_path / "flightlog_sample.csv"

    def row(**values: object) -> dict[str, object]:
        item: dict[str, object] = {name: "" for name in HEADER}
        item.update(values)
        return item

    rows = [
        row(
            timestamp_us=0,
            sequence=10,
            dropped_records=0,
            sector_seq=1,
            sector_index=2,
            roll_deg=1.0,
            pitch_deg=2.0,
            gyro_x_dps=3.0,
            gyro_y_dps=4.0,
            gyro_z_dps=5.0,
            vel_est_m_s_0=0.0,
            vel_est_m_s_1=0.0,
            vel_ref_m_s_0=0.2,
            vel_ref_m_s_1=-0.1,
            vel_err_m_s_0=0.2,
            vel_err_m_s_1=-0.1,
            vel_pid_out_m_s2_0=0.0,
            vel_pid_out_m_s2_1=0.0,
            vel_pid_p_m_s2_0=0.0,
            vel_pid_p_m_s2_1=0.0,
            vel_pid_i_m_s2_0=0.0,
            vel_pid_i_m_s2_1=0.0,
            vel_pid_d_m_s2_0=0.0,
            vel_pid_d_m_s2_1=0.0,
            vel_loop_active=0,
            throttle_us=1500,
            servo_alpha_us=1520,
            servo_beta_us=1480,
            motor_upper_us=1600,
            motor_lower_us=1605,
            motor_output_reason_name="stabilized_mix",
            ctrl_total_force_n=10.0,
            ctrl_pos_p_m_s2_0=0.0,
            ctrl_pos_p_m_s2_1=0.0,
            ctrl_vel_d_m_s2_0=0.0,
            ctrl_vel_d_m_s2_1=0.0,
            ctrl_accel_out_m_s2_0=0.0,
            ctrl_accel_out_m_s2_1=0.0,
            ctrl_target_attitude_rp_rad_0=0.0,
            ctrl_target_attitude_rp_rad_1=0.0,
            ctrl_tilt_angle_p_rad_0=0.0,
            ctrl_tilt_angle_p_rad_1=0.0,
            ctrl_tilt_rate_d_rad_0=0.01,
            ctrl_tilt_rate_d_rad_1=-0.01,
            ctrl_tilt_out_rad_0=0.10,
            ctrl_tilt_out_rad_1=-0.10,
            ctrl_attitude_error_0=0.05,
            ctrl_attitude_error_1=-0.06,
            ctrl_rate_error_rad_s_0=0.10,
            ctrl_rate_error_rad_s_1=-0.12,
            ctrl_moment_cmd_n_m_0=0.02,
            ctrl_moment_cmd_n_m_1=-0.02,
            ctrl_horizontal_command_scale=1.0,
            ctrl_moment_utilization=0.10,
            ctrl_thrust_utilization=0.20,
            ctrl_protection_flags=0,
        ),
        row(
            timestamp_us=4000,
            sequence=11,
            dropped_records=0,
            sector_seq=1,
            sector_index=2,
            roll_deg=2.0,
            pitch_deg=4.0,
            gyro_x_dps=6.0,
            gyro_y_dps=8.0,
            gyro_z_dps=10.0,
            vel_est_m_s_0=0.1,
            vel_est_m_s_1=-0.05,
            vel_ref_m_s_0=0.2,
            vel_ref_m_s_1=-0.1,
            vel_err_m_s_0=0.1,
            vel_err_m_s_1=-0.05,
            vel_pid_out_m_s2_0=0.0,
            vel_pid_out_m_s2_1=0.0,
            vel_pid_p_m_s2_0=0.0,
            vel_pid_p_m_s2_1=0.0,
            vel_pid_i_m_s2_0=0.0,
            vel_pid_i_m_s2_1=0.0,
            vel_pid_d_m_s2_0=0.0,
            vel_pid_d_m_s2_1=0.0,
            vel_loop_active=0,
            throttle_us=1510,
            servo_alpha_us=1540,
            servo_beta_us=1460,
            motor_upper_us=1700,
            motor_lower_us=1705,
            motor_output_reason_name="stabilized_mix",
            ctrl_total_force_n=11.0,
            ctrl_pos_p_m_s2_0=0.0,
            ctrl_pos_p_m_s2_1=0.0,
            ctrl_vel_d_m_s2_0=0.0,
            ctrl_vel_d_m_s2_1=0.0,
            ctrl_accel_out_m_s2_0=0.0,
            ctrl_accel_out_m_s2_1=0.0,
            ctrl_target_attitude_rp_rad_0=0.0,
            ctrl_target_attitude_rp_rad_1=0.02,
            ctrl_tilt_angle_p_rad_0=0.0,
            ctrl_tilt_angle_p_rad_1=0.0,
            ctrl_tilt_rate_d_rad_0=0.02,
            ctrl_tilt_rate_d_rad_1=-0.02,
            ctrl_tilt_out_rad_0=0.20,
            ctrl_tilt_out_rad_1=-0.20,
            ctrl_attitude_error_0=0.08,
            ctrl_attitude_error_1=-0.10,
            ctrl_rate_error_rad_s_0=0.20,
            ctrl_rate_error_rad_s_1=-0.25,
            ctrl_moment_cmd_n_m_0=0.03,
            ctrl_moment_cmd_n_m_1=-0.03,
            ctrl_horizontal_command_scale=1.0,
            ctrl_moment_utilization=0.20,
            ctrl_thrust_utilization=0.30,
            ctrl_protection_flags=0,
        ),
        row(
            timestamp_us=8000,
            sequence=13,
            dropped_records=1,
            sector_seq=1,
            sector_index=2,
            roll_deg=3.0,
            pitch_deg=6.0,
            gyro_x_dps=9.0,
            gyro_y_dps=12.0,
            gyro_z_dps=15.0,
            vel_est_m_s_0=0.1,
            vel_est_m_s_1=-0.1,
            vel_ref_m_s_0=0.2,
            vel_ref_m_s_1=-0.1,
            vel_err_m_s_0=0.1,
            vel_err_m_s_1=0.0,
            vel_pid_out_m_s2_0=0.0,
            vel_pid_out_m_s2_1=0.0,
            vel_pid_p_m_s2_0=0.0,
            vel_pid_p_m_s2_1=0.0,
            vel_pid_i_m_s2_0=0.0,
            vel_pid_i_m_s2_1=0.0,
            vel_pid_d_m_s2_0=0.0,
            vel_pid_d_m_s2_1=0.0,
            vel_loop_active=0,
            throttle_us=1520,
            servo_alpha_us=1560,
            servo_beta_us=1440,
            motor_upper_us=1940,
            motor_lower_us=1705,
            motor_output_reason_name="stabilized_mix",
            ctrl_total_force_n=12.0,
            ctrl_pos_p_m_s2_0=0.0,
            ctrl_pos_p_m_s2_1=0.0,
            ctrl_vel_d_m_s2_0=0.0,
            ctrl_vel_d_m_s2_1=0.0,
            ctrl_accel_out_m_s2_0=0.0,
            ctrl_accel_out_m_s2_1=0.0,
            ctrl_target_attitude_rp_rad_0=0.0,
            ctrl_target_attitude_rp_rad_1=0.03,
            ctrl_tilt_angle_p_rad_0=0.0,
            ctrl_tilt_angle_p_rad_1=0.0,
            ctrl_tilt_rate_d_rad_0=0.03,
            ctrl_tilt_rate_d_rad_1=-0.03,
            ctrl_tilt_out_rad_0=0.488692,
            ctrl_tilt_out_rad_1=-0.30,
            ctrl_attitude_error_0=0.10,
            ctrl_attitude_error_1=-0.12,
            ctrl_rate_error_rad_s_0=0.30,
            ctrl_rate_error_rad_s_1=-0.35,
            ctrl_moment_cmd_n_m_0=0.04,
            ctrl_moment_cmd_n_m_1=-0.04,
            ctrl_horizontal_command_scale=0.90,
            ctrl_moment_utilization=0.95,
            ctrl_thrust_utilization=0.40,
            ctrl_protection_flags=1,
        ),
        row(
            timestamp_us=250000,
            sequence=14,
            dropped_records=1,
            sector_seq=3,
            sector_index=4,
            roll_deg=1.0,
            pitch_deg=1.0,
            gyro_x_dps=2.0,
            gyro_y_dps=2.0,
            gyro_z_dps=2.0,
            vel_est_m_s_0=0.0,
            vel_est_m_s_1=0.0,
            vel_ref_m_s_0=0.0,
            vel_ref_m_s_1=0.0,
            vel_err_m_s_0=0.0,
            vel_err_m_s_1=0.0,
            vel_pid_out_m_s2_0=0.0,
            vel_pid_out_m_s2_1=0.0,
            vel_pid_p_m_s2_0=0.0,
            vel_pid_p_m_s2_1=0.0,
            vel_pid_i_m_s2_0=0.0,
            vel_pid_i_m_s2_1=0.0,
            vel_pid_d_m_s2_0=0.0,
            vel_pid_d_m_s2_1=0.0,
            vel_loop_active=0,
            throttle_us=1400,
            servo_alpha_us=1510,
            servo_beta_us=1490,
            motor_upper_us=1500,
            motor_lower_us=1500,
            motor_output_reason_name="direct_throttle",
            ctrl_total_force_n=8.0,
            ctrl_pos_p_m_s2_0=0.0,
            ctrl_pos_p_m_s2_1=0.0,
            ctrl_vel_d_m_s2_0=0.0,
            ctrl_vel_d_m_s2_1=0.0,
            ctrl_accel_out_m_s2_0=0.0,
            ctrl_accel_out_m_s2_1=0.0,
            ctrl_target_attitude_rp_rad_0=0.0,
            ctrl_target_attitude_rp_rad_1=0.01,
            ctrl_tilt_angle_p_rad_0=0.0,
            ctrl_tilt_angle_p_rad_1=0.0,
            ctrl_tilt_rate_d_rad_0=0.01,
            ctrl_tilt_rate_d_rad_1=-0.01,
            ctrl_tilt_out_rad_0=0.05,
            ctrl_tilt_out_rad_1=-0.05,
            ctrl_attitude_error_0=0.02,
            ctrl_attitude_error_1=-0.02,
            ctrl_rate_error_rad_s_0=0.05,
            ctrl_rate_error_rad_s_1=-0.05,
            ctrl_moment_cmd_n_m_0=0.01,
            ctrl_moment_cmd_n_m_1=-0.01,
            ctrl_horizontal_command_scale=1.0,
            ctrl_moment_utilization=0.05,
            ctrl_thrust_utilization=0.10,
            ctrl_protection_flags=0,
        ),
        row(
            timestamp_us=254000,
            sequence=15,
            dropped_records=1,
            sector_seq=3,
            sector_index=4,
            roll_deg=1.5,
            pitch_deg=1.2,
            gyro_x_dps=2.5,
            gyro_y_dps=2.2,
            gyro_z_dps=2.1,
            vel_est_m_s_0=0.0,
            vel_est_m_s_1=0.0,
            vel_ref_m_s_0=0.0,
            vel_ref_m_s_1=0.0,
            vel_err_m_s_0=0.0,
            vel_err_m_s_1=0.0,
            vel_pid_out_m_s2_0=0.0,
            vel_pid_out_m_s2_1=0.0,
            vel_pid_p_m_s2_0=0.0,
            vel_pid_p_m_s2_1=0.0,
            vel_pid_i_m_s2_0=0.0,
            vel_pid_i_m_s2_1=0.0,
            vel_pid_d_m_s2_0=0.0,
            vel_pid_d_m_s2_1=0.0,
            vel_loop_active=0,
            throttle_us=1410,
            servo_alpha_us=1520,
            servo_beta_us=1480,
            motor_upper_us=1500,
            motor_lower_us=1500,
            motor_output_reason_name="direct_throttle",
            ctrl_total_force_n=8.2,
            ctrl_pos_p_m_s2_0=0.0,
            ctrl_pos_p_m_s2_1=0.0,
            ctrl_vel_d_m_s2_0=0.0,
            ctrl_vel_d_m_s2_1=0.0,
            ctrl_accel_out_m_s2_0=0.0,
            ctrl_accel_out_m_s2_1=0.0,
            ctrl_target_attitude_rp_rad_0=0.0,
            ctrl_target_attitude_rp_rad_1=0.0,
            ctrl_tilt_angle_p_rad_0=0.0,
            ctrl_tilt_angle_p_rad_1=0.0,
            ctrl_tilt_rate_d_rad_0=0.01,
            ctrl_tilt_rate_d_rad_1=-0.01,
            ctrl_tilt_out_rad_0=0.10,
            ctrl_tilt_out_rad_1=-0.10,
            ctrl_attitude_error_0=0.02,
            ctrl_attitude_error_1=-0.02,
            ctrl_rate_error_rad_s_0=0.05,
            ctrl_rate_error_rad_s_1=-0.05,
            ctrl_moment_cmd_n_m_0=0.01,
            ctrl_moment_cmd_n_m_1=-0.01,
            ctrl_horizontal_command_scale=1.0,
            ctrl_moment_utilization=0.05,
            ctrl_thrust_utilization=0.10,
            ctrl_protection_flags=0,
        ),
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=HEADER)
        writer.writeheader()
        writer.writerows(rows)

    meta = {
        "complete": True,
        "errors": [],
        "begin": {"log_rate": "250"},
        "sectors": [
            {
                "sector_seq": 1,
                "sector_index": 2,
                "params": {
                    "roll_angle_kp": -8.0,
                    "roll_rate_kd": -1.0,
                    "pitch_angle_kp": -8.0,
                    "pitch_rate_kd": -1.0,
                    "pos_x_kp": 0.3,
                    "pos_y_kp": 0.3,
                    "vel_x_kd": 0.8,
                    "vel_y_kd": 0.8,
                    "vel_loop_enable": 1.0,
                    "pos_z_kp": 0.0,
                    "vel_z_kd": 0.0,
                    "yaw_rate_kd": 0.15,
                },
            },
            {
                "sector_seq": 3,
                "sector_index": 4,
                "params": {
                    "roll_angle_kp": -1.0,
                    "roll_rate_kd": -1.5,
                    "pitch_angle_kp": -1.0,
                    "pitch_rate_kd": -1.5,
                    "pos_x_kp": 0.0,
                    "pos_y_kp": 0.0,
                    "vel_x_kd": 0.0,
                    "vel_y_kd": 0.0,
                    "vel_loop_enable": 0.0,
                    "pos_z_kp": 0.0,
                    "vel_z_kd": 0.0,
                    "yaw_rate_kd": 0.5,
                },
            },
        ],
    }
    csv_path.with_name("flightlog_sample_meta.json").write_text(
        json.dumps(meta),
        encoding="utf-8",
    )
    return csv_path


def test_analyze_flight_log_segments_groups_and_flags(tmp_path: Path) -> None:
    csv_path = write_sample_log(tmp_path)

    analysis = sysid.analyze_flight_log(csv_path)

    assert analysis.row_count == 5
    assert analysis.nominal_log_rate_hz == 250.0
    assert len(analysis.segments) == 2
    assert analysis.sequence_missing_count == 1
    assert analysis.dropped_delta == 1
    assert len(analysis.gain_groups) == 2
    assert analysis.gain_groups[0].params["roll_angle_kp"] == -8.0
    assert analysis.gain_groups[0].params["pos_x_kp"] == 0.3
    assert analysis.gain_groups[0].params["vel_x_kd"] == 0.8
    assert analysis.gain_groups[0].tilt_saturation_pct > 0.0
    assert any("velocity loop is disabled" in flag for flag in analysis.flags)
    assert any("no direct range/height channel" in flag for flag in analysis.flags)
    assert any(item.loop == "速度环" and "未启用" in item.recommendation for item in analysis.tuning_advice)
    assert any(item.loop == "角度环" for item in analysis.tuning_advice)


def test_actuator_fit_and_report_outputs(tmp_path: Path) -> None:
    csv_path = write_sample_log(tmp_path)
    analysis = sysid.analyze_flight_log(csv_path)

    beta_fit = next(fit for fit in analysis.actuator_fits if fit.label == "body_x_tilt_to_servo_beta")
    assert beta_fit.slope < 0.0
    assert beta_fit.r2 > 0.9

    outputs = sysid.write_reports(analysis, tmp_path / "report", csv_path.stem)
    assert outputs["json"].exists()
    assert outputs["gain_csv"].exists()
    markdown = outputs["markdown"].read_text(encoding="utf-8")
    assert markdown.startswith(
        "# Flight Log System Identification Summary"
    )
    assert "## Tuning Advice" in markdown
    assert "水平外环未启用" in markdown
