"""H743 controls in the original scale workflow; no second application/page."""
from tkinter import ttk
import tkinter as tk


def build_integrated_view(frame):
    v=frame.vars
    conn=ttk.LabelFrame(frame,text="3  H743飞控连接与实时状态",padding=6)
    conn.pack(fill="x")
    ttk.Label(conn,text="飞控串口").grid(row=0,column=0,padx=3)
    frame.host_bridge.gui.fc_port_combo=ttk.Combobox(conn,textvariable=v["fc_port"],width=12)
    frame.host_bridge.gui.fc_port_combo.grid(row=0,column=1,padx=3)
    ttk.Label(conn,text="波特率").grid(row=0,column=2,padx=3)
    ttk.Entry(conn,textvariable=v["fc_baud"],width=9).grid(row=0,column=3,padx=3)
    ttk.Button(conn,text="连接H743台架",command=frame.connect).grid(row=0,column=4,padx=4)
    ttk.Button(conn,text="断开连接",command=frame.disconnect).grid(row=0,column=5,padx=4)
    ttk.Label(conn,text="AEO CRM2413-KV1300").grid(row=0,column=6,padx=5)
    ttk.Button(conn,text="电调KV设为1300",command=frame.write_esc_kv).grid(row=0,column=7,padx=4)
    frame.telemetry_text=tk.StringVar(frame,value="上桨 -- eRPM    下桨 -- eRPM    电压 -- V\nDShot电流：上桨 -- A    下桨 -- A    合计 -- A    输入功率 -- W")
    ttk.Label(conn,textvariable=frame.telemetry_text,wraplength=900,font=("Microsoft YaHei UI",11)).grid(row=1,column=0,columnspan=7,sticky="w",padx=4,pady=5)
    cfg=ttk.Frame(conn);cfg.grid(row=2,column=0,columnspan=7,sticky="ew")
    ttk.Label(cfg,text="直接使用电转速eRPM，无需磁极数；电流只使用DShot分路回传。",wraplength=650).pack(side="left",padx=3)
    ttk.Label(cfg,text="本次油门上限%").pack(side="left",padx=4)
    ttk.Entry(cfg,textvariable=v["max_pct"],width=5).pack(side="left")

    frame.setup_area=ttk.Frame(frame)
    def toggle_setup():
        if frame.setup_area.winfo_manager():
            frame.setup_area.pack_forget(); setup_button.configure(text="展开试转映射与手动控制")
        else:
            frame.setup_area.pack(fill="x",after=setup_button); setup_button.configure(text="收起试转映射与手动控制")
    setup_button=ttk.Button(frame,text="展开试转映射与手动控制",command=toggle_setup)
    setup_button.pack(anchor="w",pady=5)
    from .mapping_view import build_mapping_view
    build_mapping_view(frame)
    manual=ttk.LabelFrame(frame.setup_area,text="H743上下桨手动控制",padding=6);manual.pack(fill="x",pady=6)
    frame.manual_upper=tk.DoubleVar(frame,value=0);frame.manual_lower=tk.DoubleVar(frame,value=0)
    frame.manual_hold=tk.StringVar(frame,value="3")
    for row,(label,var) in enumerate((("上桨油门%",frame.manual_upper),("下桨油门%",frame.manual_lower))):
        ttk.Label(manual,text=label).grid(row=row,column=0,padx=3)
        ttk.Scale(manual,from_=0,to=100,variable=var).grid(row=row,column=1,sticky="ew",padx=6)
        ttk.Entry(manual,textvariable=var,width=6).grid(row=row,column=2,padx=3)
    manual.columnconfigure(1,weight=1)
    ttk.Label(manual,text="保持（秒）").grid(row=0,column=3,padx=5)
    ttk.Entry(manual,textvariable=frame.manual_hold,width=6).grid(row=0,column=4)
    ttk.Button(manual,text="台架解锁（零油门）",command=frame.manual_arm).grid(row=0,column=5,padx=5)
    ttk.Button(manual,text="应用上下桨油门",command=frame.manual_apply).grid(row=1,column=5,padx=5)
    ttk.Label(manual,text="滑杆只改目标；点击应用才输出，到时停止。自动扫描与手动控制互斥。",wraplength=800).grid(row=2,column=0,columnspan=6,sticky="w",pady=3)

    scan=ttk.LabelFrame(frame,text="采集 → 实验库 → 训练与效果",padding=8);scan.pack(fill="x")
    frame.smart_mode=tk.StringVar(frame,value="自动补数（换电继续）")
    frame.custom_scan=tk.BooleanVar(frame,value=False)
    frame.auto_rate=tk.BooleanVar(frame,value=True)
    frame.scan_summary=tk.StringVar(frame,value="同一电量下连续扫油门网格，先补实验库缺口，不空转等降压；低压停机后由你换电并点击继续。")
    frame.stop_voltage=tk.StringVar(frame,value="10.8")
    frame.auto_minutes=tk.StringVar(frame,value="60")
    frame.auto_points=tk.StringVar(frame,value="3000")
    top=ttk.Frame(scan);top.pack(fill="x")
    ttk.Label(top,text="本次任务").pack(side="left")
    ttk.Combobox(top,textvariable=frame.smart_mode,values=("自动补数（换电继续）","快速检查","标准采集","补充测量"),state="readonly",width=19).pack(side="left",padx=5)
    ttk.Label(top,text="最高油门%").pack(side="left",padx=(8,3))
    ttk.Entry(top,textvariable=v["max_pct"],width=5).pack(side="left")
    ttk.Label(top,text="3S换电电压(静置) V").pack(side="left",padx=(8,3))
    ttk.Entry(top,textvariable=frame.stop_voltage,width=6).pack(side="left")
    ttk.Button(top,text="预览本次计划",command=frame.preview_scan).pack(side="left",padx=6)
    ttk.Button(top,text="开始 / 换电继续",command=frame.start).pack(side="left")
    ttk.Button(top,text="最大推力测试（100%）",command=frame.start_max_thrust).pack(side="left",padx=6)
    ttk.Label(scan,textvariable=frame.scan_summary,wraplength=850).pack(fill="x",pady=6)
    result=ttk.Frame(scan);result.pack(fill="x",pady=4)
    ttk.Button(result,text="实验库：选择训练与验证",command=frame.open_library).pack(side="left")
    ttk.Button(result,text="生成模型报告",command=frame.analyze).pack(side="left",padx=6)
    ttk.Button(result,text="建立查补表",command=frame.build_throttle_model).pack(side="left",padx=6)
    ttk.Button(result,text="查补表实测验证",command=frame.start_model_validation).pack(side="left",padx=6)
    ttk.Button(result,text="差速实测验证",command=frame.start_split_validation).pack(side="left",padx=6)
    frame.report_open_button=ttk.Button(result,text="查看拟合效果",command=frame.open_report,state="disabled")
    frame.report_open_button.pack(side="left")
    frame.report_summary=tk.StringVar(frame,value="每次实验自动积累；在实验库按整轮选择训练集和验证集。")
    ttk.Label(scan,textvariable=frame.report_summary,wraplength=850).pack(fill="x",pady=5)
    advanced=ttk.Frame(scan)
    def toggle():
        if advanced.winfo_manager(): advanced.pack_forget(); more.configure(text="展开高级扫描设置")
        else: advanced.pack(fill="x"); more.configure(text="收起高级扫描设置")
    more=ttk.Button(scan,text="展开高级扫描设置",command=toggle);more.pack(anchor="w",pady=3)
    ttk.Checkbutton(advanced,text="使用自定义旧扫描（勾选后才使用以下参数）",variable=frame.custom_scan).grid(row=0,column=0,columnspan=4,sticky="w")
    ttk.Combobox(advanced,textvariable=v["mode"],state="readonly",values=("单上桨","单下桨","双桨共增","二维网格","动态上桨阶跃","动态下桨阶跃"),width=16).grid(row=1,column=0,sticky="w")
    fields=(("最小%","minimum"),("最大%","maximum"),("步长%","step"),("采样频率Hz","snapshot_hz"),
            ("上桨网格%","upper_values"),("下桨网格%","lower_values"),("阶跃增量%","delta"),("阶跃次数","repeats"),
            ("旧电量标签（选填）","voltage_layers"),("桨叶/安装","prop"),("桨间距","spacing"))
    for i,(label,key) in enumerate(fields):
        row,col=divmod(i,4)
        ttk.Label(advanced,text=label).grid(row=2+row*2,column=col,sticky="w",padx=3)
        ttk.Entry(advanced,textvariable=v[key],width=21).grid(row=3+row*2,column=col,padx=3,sticky="ew")
    ttk.Button(advanced,text="准备从首层独立复测",command=frame.repeat_voltage_layers).grid(row=8,column=0,columnspan=2,sticky="w",pady=4)
    ttk.Checkbutton(advanced,text="自动选择采样频率：确认USB用30Hz，其他链路15Hz",variable=frame.auto_rate).grid(row=9,column=0,columnspan=4,sticky="w")
    ttk.Label(advanced,text="每轮最长分钟").grid(row=10,column=0,sticky="w")
    ttk.Entry(advanced,textvariable=frame.auto_minutes,width=8).grid(row=11,column=0,sticky="w")
    ttk.Label(advanced,text="每轮最多点数").grid(row=10,column=1,sticky="w")
    ttk.Entry(advanced,textvariable=frame.auto_points,width=8).grid(row=11,column=1,sticky="w")
    frame.live=tk.Text(frame,height=4,state="disabled");frame.live.pack(fill="x",pady=(6,0))
