#ifndef BSP_ESC_PROTOCOL_H
#define BSP_ESC_PROTOCOL_H

#define BSP_ESC_PROTOCOL_PWM 0
#define BSP_ESC_PROTOCOL_DSHOT300 1
#ifndef BSP_ESC_PROTOCOL
#define BSP_ESC_PROTOCOL BSP_ESC_PROTOCOL_DSHOT300
#endif
#if BSP_ESC_PROTOCOL != BSP_ESC_PROTOCOL_PWM && BSP_ESC_PROTOCOL != BSP_ESC_PROTOCOL_DSHOT300
#error Unsupported ESC protocol
#endif

#endif
